enum ITEM_TYPE {KEY, CONSUME, WEAPON, ARMOR}

enum PAUSE_PAGE {MAIN, INVENTORY, STATS}
enum INV_TAB {KEY, CONSUME, WEAPON, ARMOR}

enum BSTATE 
{
    INTRO,
    PLAYER_MENU,
    PLAYER_RESOLVE,
    ENEMY_TELEGRAPH,
    ENEMY_INPUT,
    ENEMY_RESOLVE,
    WIN,
    LOSE
}

enum DIR {U, R, D, L}
